<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="هلوفيرا للتأمين — تجربة فاخرة لتأمين السيارات عالية القيمة في الإمارات."><title>هلوفيرا للتأمين | تأمين السيارات الفاخرة</title><link rel="stylesheet" href="/styles.css"></head><body>
<div class="service-bar"><div class="wrap"><span>تغطية في جميع إمارات الدولة</span><span>أبوظبي · دبي · الشارقة · عجمان · أم القيوين · رأس الخيمة · الفجيرة</span></div></div>
<header class="header"><nav class="nav wrap"><a class="brand" href="/"><span class="brand-mark">هـ</span><span>هلوفيرا<br><small>للتأمين</small></span></a><button class="menu" aria-label="فتح القائمة" aria-expanded="false">☰</button><div class="nav-links"><a class="active" href="/">الرئيسية</a><a href="/plans/">خطط التأمين</a><a href="/vehicles/patrol/">السيارات</a><a href="/claims/">المطالبات</a><a href="/contact/">تواصل معنا</a></div><a class="nav-action" href="/contact/#quote">اطلب عرضًا</a></nav></header>
<main>
<section class="campaign-hero"><a href="#choose-car" aria-label="ابدأ طلب تأمين سيارتك"><img src="/assets/halovera-emirati-insurance-hero.png" alt="مستشار تأمين إماراتي أمام سيارة فاخرة"></a></section>
<section class="vehicle-picker" id="choose-car"><div class="wrap"><div class="picker-card"><div class="picker-intro"><div class="kicker">ابدأ من سيارتك</div><h2>اختر سيارتك</h2><p>نعرض خيارات التأمين لمختلف الماركات والفئات في الإمارات.</p></div><form class="quote-mini" data-demo-form><select aria-label="نوع السيارة" required><option value="">اختر الماركة أو الفئة</option><option>نيسان باترول</option><option>تويوتا لاندكروزر</option><option>لكزس LX / GX</option><option>مرسيدس G-Class / GLS</option><option>رنج روفر</option><option>بي إم دبليو X7 / X5</option><option>أودي Q8 / Q7</option><option>بورش كايين</option><option>كاديلاك إسكاليد</option><option>جي إم سي يوكن</option><option>شفروليه تاهو / سوبربان</option><option>فورد إكسبيديشن</option><option>إنفينيتي QX80</option><option>بنتلي / رولز رويس</option><option>سيارة رياضية</option><option>سيارة كهربائية</option><option>سيدان أو كروس أوفر</option><option>سيارة أخرى</option></select><input aria-label="سنة الصنع" type="number" placeholder="سنة الصنع" min="1990" max="2027"><button class="btn gold">ابدأ الطلب</button><div class="success" style="grid-column:1/-1">تم تجهيز الطلب المبدئي. أضف وسيلة التواصل الرسمية عند اعتماد الموقع.</div></form></div><div class="car-types" aria-label="أنواع السيارات المشمولة"><span>دفع رباعي</span><span>سيدان</span><span>كروس أوفر</span><span>رياضية</span><span>كهربائية</span><span>كلاسيكية</span><span>تجارية خفيفة</span><span>فاخرة</span></div></div></section>
<section class="patrol-lead"><img src="/assets/atlas-patrol-uae.webp" alt="نيسان باترول بيضاء فاخرة في دبي"></section>
<section class="hero hero-message"><div class="hero-copy"><div class="kicker">حماية مصممة لسوق الإمارات</div><h1>سيارتك ليست<br>مجرد وسيلة.</h1><p>تأمين شامل لمختلف السيارات، من مركبتك اليومية إلى سيارات الدفع الرباعي والفئات الفاخرة، بخيارات واضحة تحفظ قيمة سيارتك وراحتك على الطريق.</p><div class="emirates-note"><strong>تغطية في جميع الإمارات</strong><span>أينما تسكن، نساعدك على بدء طلبك ومراجعة احتياج سيارتك.</span></div></div></section>
<section class="trust-row"><div class="wrap"><div class="trust-item"><b>إصلاح الوكالة</b><span>راجع الخيار حسب الوثيقة</span></div><div class="trust-item"><b>قيمة متفق عليها</b><span>وضوح أكبر قبل التعاقد</span></div><div class="trust-item"><b>مساعدة الطريق</b><span>دعم داخل نطاق التغطية</span></div><div class="trust-item"><b>مطالبات منظمة</b><span>خطوات واضحة للمتابعة</span></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><h2>لكل سيارة<br>حماية تناسبها.</h2><p>لا نحصر الخدمة في أربعة موديلات؛ نستقبل طلبات مختلف الماركات والفئات، ونخصص العرض حسب قيمة السيارة وسنة الصنع والاستخدام.</p></div><div class="vehicle-grid"><a class="vehicle-card" href="/vehicles/patrol/"><img src="/assets/atlas-patrol-uae.webp" alt="باترول جديد أبيض"><div class="vehicle-copy"><div class="kicker">NISSAN PATROL</div><h3>قوة يومية. حماية محسوبة.</h3><p>للباترول الجديد ومختلف فئاته.</p><span class="text-link">تعرّف على التغطية ←</span></div></a><a class="vehicle-card small" href="/vehicles/lexus/"><img src="/assets/atlas-lexus-uae.webp" alt="لكزس LX بيضاء"><div class="vehicle-copy"><div class="kicker">LEXUS LX</div><h3>رفاهية تستحق الدقة.</h3><p>للـLX والسيارات ذات التجهيزات المتقدمة.</p><span class="text-link">استكشف لكزس ←</span></div></a></div><div class="brand-list"><span>نيسان</span><span>تويوتا</span><span>لكزس</span><span>مرسيدس</span><span>رنج روفر</span><span>بي إم دبليو</span><span>أودي</span><span>بورش</span><span>كاديلاك</span><span>جي إم سي</span><span>شفروليه</span><span>فورد</span><span>إنفينيتي</span><span>تسلا</span><span>بنتلي</span><span>رولز رويس</span><span>وغيرها</span></div></div></section>
<section class="section navy"><div class="wrap"><div class="section-head"><h2>من اختيار الخطة<br>إلى وقت المطالبة.</h2><p>تجربة هادئة ومباشرة تركز على ما يهمك فعلًا.</p></div><div class="steps"><div class="step"><span>01</span><h3>عرّفنا بسيارتك</h3><p>الموديل، السنة، القيمة، ونمط الاستخدام.</p></div><div class="step"><span>02</span><h3>راجع التفاصيل</h3><p>الإصلاح، التحمل، التغطيات الإضافية والاستثناءات.</p></div><div class="step"><span>03</span><h3>اختر بوضوح</h3><p>قارن الخيارات قبل إصدار الوثيقة من الجهة المرخصة.</p></div></div></div></section>
<section class="section cream" id="plans"><div class="wrap"><div class="section-head"><h2>ثلاث درجات<br>من العناية.</h2><p>أمثلة تنظيمية لتوضيح مستويات الخدمة؛ يعتمد العرض النهائي على شركة التأمين وشروط الوثيقة.</p></div><div class="plan-grid"><div class="plan"><div class="plan-label">ESSENTIAL</div><h3>الأساسية</h3><p>لبداية واضحة مع المتطلبات الأساسية.</p><ul><li>تغطية وفق الوثيقة المختارة</li><li>مساعدة مطالبات إرشادية</li><li>خيارات تحمل متعددة</li></ul><a class="btn" href="/plans/">التفاصيل</a></div><div class="plan featured"><div class="plan-label">SIGNATURE</div><h3>سيغنتشر</h3><p>للسيارات الفاخرة والاستخدام اليومي.</p><ul><li>مراجعة إصلاح الوكالة</li><li>مساعدة الطريق عند توفرها</li><li>خيارات سيارة بديلة</li></ul><a class="btn gold" href="/plans/">التفاصيل</a></div><div class="plan"><div class="plan-label">PRESTIGE</div><h3>بريستيج</h3><p>للمركبات عالية القيمة والاحتياج الخاص.</p><ul><li>مراجعة قيمة السيارة</li><li>تغطيات إضافية مختارة</li><li>خدمة متابعة مخصصة</li></ul><a class="btn" href="/plans/">التفاصيل</a></div></div></div></section>
<section class="section"><div class="wrap"><div class="banner"><h2>القرار الأفضل يبدأ<br>بقراءة التفاصيل.</h2><a class="btn" href="/contact/#quote">اطلب مراجعة احتياجك</a></div></div></section>
</main>
<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="/"><span class="brand-mark">هـ</span><span>هلوفيرا<br><small>للتأمين</small></span></a><p>واجهة فاخرة لخدمات تأمين المركبات في الإمارات.</p></div><div><h3>استكشف</h3><a href="/plans/">الخطط</a><a href="/vehicles/patrol/">باترول</a><a href="/vehicles/lexus/">لكزس</a></div><div><h3>المساعدة</h3><a href="/claims/">المطالبات</a><a href="/contact/">التواصل</a></div></div><div class="legal">المعلومات المعروضة تعريفية ولا تمثل عرض تأمين ملزمًا. تبدأ التغطية فقط بعد موافقة وإصدار وثيقة سارية من مزود تأمين مرخّص في دولة الإمارات. © 2026 هلوفيرا للتأمين.</div></div></footer><script src="/script.js"></script></body></html>
